site_name: MSYS
site_url: https://msys-docs.readthedocs.io/en/latest/?badge=latest

theme:
  name: material
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.png
  favicon: img/favicon.png
  language: en

repo_url: https://github.com/willi-z/msys
edit_uri: https://github.com/willi-z/msys/tree/main/docs
docs_dir: docs
site_dir: build/wiki


plugins:
    - search
    - mkdocstrings

nav:
    - Introduction:
        - Home: index.md
        - Getting Started: getting-started.md
    - Tutorials:
        - Building a Process: tutorials/processing.md
        - Install an Add-On: tutorials/add-on.md
    - Explanations:
        - Processing: explanations/processing.md
        - Modules: explanations/module.md
        - Types : explanations/types.md
    - How-To:
        - Write Basic Extensions: how-to/extensions.md
        - Add new Types: how-to/type.md
        - Add new Modules: how-to/module.md
        - Add new Funktionalities: how-to/classes.md
    - References:
        - Pluginsystem: references/plugins.md
        - Source-Code: references/source.md
        - Implementations: references/projects.md
    - Development:
          - Writing Tests: development/tests.md
          - Writing Documentation: development/documentation.md
    - About: about.md

